---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        address: |-
          {{ .flux_discord_webhook }}
  refreshInterval: 15m
  data:
    - secretKey: flux_discord_webhook
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e96ee6e3-1fb8-4049-a605-b0ba0043d59d
        property: flux_discord_webhook
