---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-alertmanager-discord
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/monitoring/alertmanager-discord/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-bitwarden
  dependsOn:
    - name: cluster-apps-external-secrets-stores
