---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads
spec:
  capacity:
    storage: 16T
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.10.31
    path: /mnt/SuperPool/shares
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - relatime
    - nocto
    - noacl
    - nconnect=8
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  volumeName: downloads
  storageClassName: ""
  resources:
    requests:
      storage: 16T
