---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./media-pvc.yaml
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./kavita/ks.yaml
  # - ./overseerr/ks.yaml
  # - ./plex/ks.yaml
  # - ./plex-auto-languages/ks.yaml
  # - ./plex-meta-manager/ks.yaml
  - ./tautulli/ks.yaml
  # - ./wizarr/ks.yaml
