---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./downloads-pvc.yaml
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./tautulli/ks.yaml
  - ./radarr/ks.yaml
