ansible_become_pass: ENC[AES256_GCM,data:4EwQh8XfhO6NJfHR,iv:V4h/B4lnx/PNgypmFCaRZVqivV/1KFwrIwHANgoIEHI=,tag:lggxgcajCabpvP7U7Zc7zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5STFUbDFVSHhHZlhCeHhO
            dFZKdDIyODdiNWQ0bHNKY0FNMVVQOS9VQ2tVCkRYSUtkRytPYlc4S29pYnBBMEhx
            eWl4cVVWZ29jTGEzS3hzL1BxVjIvaTgKLS0tIEZUOWhQQzZLVnVKT3M1Q2Ywd0or
            aDc4SCtncnhBWkwxcTJhNitTUFRDQ0EKslgUynLlhkFgSH6kFjqFl/xLaMzvybEt
            wa71axW6Qs8UsXVeAFhmGmY8rNFru/fmnfcGENhJOuoTkpj8PMS88A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:14:59Z"
    mac: ENC[AES256_GCM,data:gqmTzhG8DdvI+lE79TNVKitxakOjHuFviuKPui4Gxh276Xmq4mwE9Pm9IYpLaCugb9brmKQqUiaTFE+/mQuyTqBFcTWi0BkminH5NPL+AlLhYZdwfaOfT6pZT0ht2wEDN2yF4CxdQLCY6DP0kqjAnxmtzqKOJK1IE3eDkVQuHWs=,iv:O8fTqZ/edb/59I0nv95nvmc6neI/eoVOnkh96B/77wA=,tag:v6EqCXOPjTBmyX7AV/hQuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
