ansible_become_pass: ENC[AES256_GCM,data:ygLDYSmUVg820Mhx,iv:iJh3137dGZH60CQ+wuhNJfXhtSA7JaYYJA2fsT8+Pjs=,tag:szwSk7a2Ru5fTlsj+j7ywg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhK0FhV3JZYkJQYU03M09n
            am94TWt1YXArUE1ZTDNNRk9Tb2VqSHIvU1hJCnNRbXI2bzVCb01kYVVsbkQ0bzhq
            SGpGcWNNL3ZtWW9pMk15dnBreHhYdzgKLS0tIGt0WHNMTHdZTjFIM3RKdGRwbGNy
            SE5LNWVXam4wd1o0OWcxd0VTekc4aW8KHvYy7nlkAowIiLI5TOLEwln33Y+hrkck
            clZmQy2fWllSU75ENiWTxmO9znH3k5V/PCiasSvkcrufN8ijsZq1jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:43:42Z"
    mac: ENC[AES256_GCM,data:Jmu/J/a9poqHpx+L2UBS3EkYLYPusRyjjIKDPEFfi00GHcyMr57uZnAaIWZMjhXsQ/fqJd0uOeuOgmXVcCCBWQdnh/V9Loygg6ANHxpqWuW79ImP4YBB2evoghN6AE6F5nyz+dFYETx4LLfTsgFYAV5XdoHt5l2YqvZ45Ylpa8U=,iv:Nca9VnHijS6UMSkV7mTgAkHgjr8ud1GvxZc3Gcx1umg=,tag:4ZFEhTQzKpD4zt++Xiyu8A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
