ansible_become_pass: ENC[AES256_GCM,data:qjyChug6CLHeZSll,iv:5HYG1/RbSxT+wL+ML3KI1vyz8bPjOfl/pOhyUt9q32U=,tag:b9x71kKGsaiZrrnAO+45Rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaklRV3VHWlErd2Jnc2J3
            SHBDVCtXcHg1M2RjMzBZYzAyT0Fma3BHQVcwCjdHRjJuN2pHWGEwYmJhcU5DS1ln
            c2FEOHFDSWJGWXZ3SVVYOGErS1c3clEKLS0tIHhIVGpPdmlhZSt2SFFnQ2drU3Ra
            ak9iSHdrdHhqWnJJQTNmUXA0Tnk0UDAKJxcfqo9CMIHbOc31y/bQvsFX8IjRuxPM
            VDaCItzXS06KTpuijuzG2Euc/UnJ/eteNH8NK9BL6wblNFNBm/oKSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-18T03:12:31Z"
    mac: ENC[AES256_GCM,data:sPzE1MIXI/nx1NB977VRl3CGLJGHenFM9FIL2WJh8Fi9kGy4on2S6RJ8b6nrumzLu26WaPIWxxOcHkFA+hWi303rDxW87VzGmFNLoXYD3ydg3hsrzlKmLaN0MclrW/WGAte1KQuFpekvoMnWQP8dbj0+HS5+D0S/QejAUaK+TMs=,iv:Lx8Gsaeh9Wqr2G8rDcEd/PlOxRfCLYgPNaHluvsLpw8=,tag:dPWmTh2o8Cyu7l3amYrY4A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
