ansible_become_pass: ENC[AES256_GCM,data:dkWvGxSgONMTaHsM,iv:EkTzRDr5emfYj6A8WgMTtVJTZtwlxhqOmlwrWD4KcLE=,tag:Mhyq8j3HDdP/k+4Ur0QT5A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OXNNOS85dWpoSkxoU3o0
            V1JES2xyZzF1cjdFWXNlM3oyQnlpb2IrYWo4CjdpWHk3WGJpM1VjZlJ2RWYxZjVC
            UHczRFFTdmsvbzRDZWR0YVN1KzJDNGcKLS0tIGtPMHVMTm9WbkxHYlBjOE54dnpH
            dGxvYi9HdlFBeU53UVV0ZHhHdkxBNWsKZ9Dsm2zKt2fc99Wo/1DEOd+X+ngGYwYR
            dwItvxBLE4uxgiDXEDmuntWJWTn5gcIP9wB+XGfU2ypmIBAqrIsCng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-18T03:12:31Z"
    mac: ENC[AES256_GCM,data:ZTnwFDTpaWvV52AgpCMv1P2xkYw0y4qPLPXEfrOU0sfl140ZJiym5B0ze6Oq0vH5faqjOBFgpbrNeNaOuiazano/MMSRH2vgjFp3q1+aZYM8vj5uhR1/PW61JVDWe9usaRX5VJjDH/cUNxlp2td4WTCpVuI5NCH0Yd/QKBG+uKc=,iv:lt5Ypa6EwUXXB0moljZFB3a+RLPbpDhF3cdgCtI9xIk=,tag:sRlo3y9/NSKq6cf+rXaqZg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
