ansible_become_pass: ENC[AES256_GCM,data:NUndOERdtVBv7UHs,iv:mGE1UCDiWsfDIQQiXfaMMfHOJQy44j8k1wUbWDvkH3A=,tag:MYb+9P9L8+PEwU/GX+pWEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRmFuc3A0TFp3SXhSVVRr
            eDN3MGFGRXB0cVRPNjBTaGVDWkRWT0RXSlZvCm1Kc3MzSVF1NDAzQzlaQWl3Rjhk
            WWlsRnhhZHRlaGdibkdqam1qVEJqWnMKLS0tIGJjcjVHYW1zYTI3WGtiV0pzSEVM
            YzVOYTE1dEZ3Rnh6OEt0WmdnbWt3cTQK4I0Pq/8y4PJiF/8nAglPZEDxT4U482bU
            dGokTvTxvf6kZwEkKBC8LfqcxApuZ9dM+JSwXw80OM7o0k70dmNsUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:11:44Z"
    mac: ENC[AES256_GCM,data:OepcO91glNKX/CDlqBF+B0JccgRk9YDXFitZqON3XPUeHWJbuxsoOaK3nHvQmsp2TThCvb32N146/XMXp5s0OlPUGX50FJ2Sl59jltouW2pnUiheNl0HXfNE0kOkvr6/UJ+SVlyzOapmwEdMhPatcnwLuOSdFc6Q58TWgo1EycE=,iv:0GlY601zZ9UI7sqVJd17KPq/2Zef7sVw3YjWdq0kBLQ=,tag:20Ad+sCZqJZu7j7HSMrivA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
