ansible_become_pass: ENC[AES256_GCM,data:hCHJwwzWEOTfJvAc,iv:khAYnOzYLq1hHh/owBGLnb4AGqTltSD8tkI6Fw/5ON4=,tag:VFFkwKfxxHSBOHWu2XHocw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZVVLOEZuWmtpTXV6cEw0
            RDZJK3JGV0JSRzRROTBteU9SRmg5VWsrcld3Cld1TG82Z3dyYmRvMEtNV3ZtWXgw
            QSttQnVjYVVybXcrSnpMd01HUVdvTHMKLS0tIGpoMWZlSXpKV3ZwYmhtMi9uRHRU
            aUt2K2t6Q1hwQU5ad3o2OXBCSElUbWMKiU4RTOnkh+UTooiLUmgpNEq7l8UdqVsZ
            uK7ocTPiV1rCJKI6r/kEK7HvS5gJNUk4NfQTgHa5d0PWmC44YwxHFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:43:43Z"
    mac: ENC[AES256_GCM,data:gs41ugQQf3WcPG7zdOHy6BoN8LaaFywx0FMYElT36wRgs3fJOZOvg++nv6hBGFBIgT//oJFog3JoLtKAzxo03CioINhEGQQOxbw5w7X6tDKHihKqJqsVszNoUplTTNRDOmHJXGWeRaBs+WdoDKhKjy2fsovXNrAhOQmSkA9J/pk=,iv:txXkyhP5JPQjkmmBEXoYQLPPCNO9+rueI3u+T4YdW4o=,tag:5pnW4c9W+FthdyQ7r8sb7w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
