ansible_become_pass: ENC[AES256_GCM,data:4ysgRg6AtkKHLnUu,iv:qKQNJgLLaZ+dLneqCgiN+P3fpUby6s3TH3peH+ScH94=,tag:RAqIXH/sL/9HdPb4FBxF6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VkhJbUVGM0N0QWN4VjE1
            eDZ2RlFJdEQyRmpHWk1Ed3ltSFkxa1RqNWlRCi9KZnduZCs2d0tZMzJQK3g5dTR3
            UWRlL2lHbDVmUHpkekpLUjJHYkxhT1EKLS0tIGpaZlRCWU5laUpoQXorcmhDYUtm
            YSsxMXRXbDlqUkN3cnFjRHF6TU5QYWMKOxmaY825CeLP8uaf9ue9ix37cwm1QQnF
            QvanRM4jqvUlbuBGKuPLzD1D2U/WDqGv+aTMo/MKUnN5knAn6z8AAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:28:08Z"
    mac: ENC[AES256_GCM,data:qS4hNAktJ483JdyEqOkKq7tX301CDgKCAV8sI6eJqaVa/It77Ic7a74R1R9aYxz++Dznxr0OE26/YndLNQjEMc9+ggRTsuKZrp7+p1efzQ0cX//DDu2kTnN5xXmHgAtz9AD5/pcO5D1Xc9uT/7IeT3/1wJWIgy4YE3/GZhZdi5c=,iv:UkWfUrbleH7Vf2u2KE2Ib13cT8qbx1kwDsOxdmmvV+k=,tag:uPmVMqWscIHwZkEAKK8B0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
