---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hajimari-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Hajimari
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: false
          hide-url: false
        dns:
          query-name: hajimari.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: discord
