---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sabnzbd-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        SABNZBD__API_KEY: "{{ .SABNZBD__API_KEY }}"
        SABNZBD__NZB_KEY: "{{ .SABNZBD__NZB_KEY }}"
  data:
    - secretKey: SABNZBD__API_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa
        property: sabnzbd_api_key
    - secretKey: SABNZBD__NZB_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa
        property: sabnzbd_nzb_key
