---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: grafana
        group: Monitoring
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: grafana.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: discord
