---
apiVersion: batch/v1
kind: Job
metadata:
  name: "list-${rsrc}-${ts}"
  namespace: "${ns}"
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        setGateway: "false"
        app.kubernetes.io/created-by: volsync
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
        - name: list
          image: docker.io/restic/restic:0.16.2
          args: ["snapshots"]
          envFrom:
            - secretRef:
                name: "${rsrc}-volsync"
