---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-webhook-gatus-ep
  namespace: external
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Flux-Webhook
        group: external
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: flux-webhook.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushovera
