apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:SRhvuIPQLsArDfBjUBeONF4JG+Jf86aB,iv:F6939eKjR6EAtd4IxtjUiznYCFSwbigRfa1Lj+2xjyM=,tag:vB4BmHqvL91SwbOxCwSsaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZCtpMS83OHp5c1FKeERV
            U3E1UUgwL2ozMGl6REF1K1FOY1ZqbGtPZVhZCldibnBHM3RvTUI5TFFVN0poR3k5
            MzZQVmlzQjJxN0NCRm9KS01YNWVISXcKLS0tIHpBQVp0amc1ekJwa3JEVzkxQm4x
            cEJ4aUxTME1TSTJvMjlvQVd0ZUVJWVEKHgvicCu++4IZ+lQDPdNZpOOlMUbOWD6g
            8uyN4HIwCUPY0ZR3FbmHo6GwAwpRrXNNfgBSEP/l57bpgVZA+8A52g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:15:30Z"
    mac: ENC[AES256_GCM,data:CJle5rQ4dHTCf5aTnrgQmzPa4TjdceAGOO74iiCGSES/n+zbDGjy6SDvttkV0KmiLLF/BfdrPwkqCDBMlccsQcz3pFFpA3OaE3vSpLE7GuX4RouDGGh7NJLeZdnmJJPmbu/kMdXero6Jb5tUg1m88sYkthpNkqO1/8mUJExMJic=,iv:IMsh1ZKZjb8x5zNQqSag7zw2pMOdjjl3aiRv5j1m5wk=,tag:bgv2pOMdIYxZ6b4Tvsd5wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
