apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:D+2zAESKDwc9My4IkUs+Hommt3Zv1F4G,iv:cqVd1NliTYKHEZzIZtCo80ZS9AymiyapxSaPYF2JQqM=,tag:aDvlX5GNBbYUiGMHyqqtew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSGhBUHExZ3FHaFI3TTJK
            Z2ZUYUhhRkZKcVpETHFrRmFFK2FBenpNd0EwCmVLQnNwS2o4VmtpUlIvZHZPVEhK
            U2RDSi8ybDRMbmRjWDdtdlo4VmdCdHMKLS0tICtQYUdBYmc4bFlqSEliR0RaTm14
            SHhIcVlyWHRJbXdla253OE91SmVYT0kKRVBUoh3zeqRaImnyvzBYR8XCAkEvcc1p
            gsIitz0zC00VRQunLX9+z+RkGcbsxt/xgNxgudRR0o492lDJQj4f3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:44:14Z"
    mac: ENC[AES256_GCM,data:a9OC+8GyqR7zVdLTdC253vDDhP8y3TvWtmmY+a6b0v6+frxXOpFF/N7Zc9vZ77POC066fIZWIragv2IusUDxiPRzEFwYP/+I/xzjt5Q1Olq5P+VQ2R3lTsAumHAXpVHJetaGJZ8bD3dh1pZwBO3xgu5KZxYlQmmOgGP7JWS8wEY=,iv:M8iZ0G5+QgF5EXxQ7YTVI/PbMEq9cGYiTUMBLfGZMQU=,tag:crUQcr2JgDF9qQSZl5d9YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
