---
kubernetes:
  children:
    master:
      hosts:
        microserver-81:
          ansible_user: miguel
          ansible_host: 10.0.10.181
        microserver-82:
          ansible_user: miguel
          ansible_host: 10.0.10.182
        microserver-83:
          ansible_user: miguel
          ansible_host: 10.0.10.183
    worker:
      hosts:
        microserver-84:
          ansible_user: miguel
          ansible_host: 10.0.10.184
        microserver-85:
          ansible_user: miguel
          ansible_host: 10.0.10.185
        microserver-91:
          ansible_user: miguel
          ansible_host: 10.0.10.191
        microserver-93:
          ansible_user: miguel
          ansible_host: 10.0.10.193
