---
endpoints:
  - name: prometheus
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: true
      hide-url: true
    dns:
      query-name: prometheus.${PUBLIC_DOMAIN}
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover
