---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homebridge-downstairs
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/oznu/homebridge
      tag: "2023-01-08"
    controller:
      strategy: Recreate
    env:
      TZ: "America/New_York"
      ENABLE_AVAHI: "1"
    service:
      main:
        ports:
          http:
            port: &port 8581
          webhook:
            port: 22987
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    persistence:
      homebridge:
        enabled: true
        existingClaim: homebridge-downstairs-config
      startup-sh:
        enabled: true
        type: configMap
        name: &config homebridge-downstairs-startup-sh
        mountPath: /homebridge/startup.sh
        subPath: startup.sh
        defaultMode: 493
    configMaps:
      config:
        enabled: true
        nameOverride: startup-sh
        data:
          startup.sh: |-
            #!/bin/sh
            npm install --save homebridge-config-ui-x@latest
            npm install --save homebridge-hubitat-tonesto7@latest
            npm install --save homebridge-camera-ffmpeg@latest
            npm install --save homebridge-envisalink@latest

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: homebridge-downstairs
          hajimari.io/icon: simple-icons:homebridge
        hosts:
          - host: &host "homebridge-downstairs.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /login
            port: *port
          initialDelaySeconds: 30
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    resources:
      requests:
        cpu: 40m
        memory: 298Mi
      limits:
        memory: 298Mi
