---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recyclarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RADARR_API_KEY: |-
          {{ .radarr_api_key }}
        SONARR_API_KEY: |-
          {{ .sonarr_api_key }}
  data:
    - secretKey: radarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa
        property: radarr_api_key
    - secretKey: sonarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa
        property: sonarr_api_key
