---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SONARR__API_KEY: "{{ .sonarr_api_key }}"
        SONARR__POSTGRES_HOST: &dbHost "{{ .init_postgres_host }}"
        SONARR__POSTGRES_PORT: "5432"
        SONARR__POSTGRES_USER: &dbUser "{{ .init_postgres_user }}"
        SONARR__POSTGRES_PASSWORD: &dbPass "{{ .init_postgres_pass }}"
        SONARR__POSTGRES_MAIN_DB: sonarr_main
        SONARR__POSTGRES_LOG_DB: sonarr_log
        # Postgres Init
        INIT_POSTGRES_DBNAME: sonarr_main sonarr_log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .init_postgres_super_pass }}"
  data:
    - secretKey: init_postgres_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_host
    - secretKey: init_postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_user
    - secretKey: init_postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_pass
    - secretKey: init_postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_super_pass
    - secretKey: sonarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa #media_secrets
        property: sonarr_api_key
