---
apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-gatus-ep
  namespace: longhorn-system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Longhorn
        group: internal
        url: https://longhorn.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://10.0.10.1:53
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
