apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:BfOpuxfQ2c9Xfj4ykReC/Krf3QHIohK88XkFt1riZVytn9GE8jIWQA==,iv:k2NCI0aXNR9tQRvEB6QoKijxNAQi/gxGzAOs5ndEkuM=,tag:i/VnGwaUTKEJ8QYYHWj2cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkT1JJanNtbGNLVTFXR0p3
            V0d1OEpxVGVHeHF1NTFTUzhlc3RIOUFyNnkwCmw0OTg4VHNOQ0lRWkxaaDAwbHRu
            ejN2WGJwWFRBbGlDZnNLMkcxbG5sR3MKLS0tIExheHZ0ZEdpSXp6Z3FFQURZZE1Y
            ZVh6amI4VjB4eVJQM1ZhNzJNbnRHNUUKI/9Gvh1i3nysgXZ+G/ubIAEIrOYyVy40
            swQ5ETZ+0FXIe3i+MCZHFJNGpfTbTSHannb5eOLi5bbDo3Gr6tkSXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:44:14Z"
    mac: ENC[AES256_GCM,data:xmJiaeKatPMDpJVh5P8pCyUL/ZfcnokodV2DMhf8BW/PcbjJXBR1uC64Qsw/ijhJSgxSP9yM0bgPTOruUcpKAp8omK0+7MSHnF9TXF3PSOGagnJEFwNte+r0u0NX3rRouJZIUSyJrdwTrkhwCoPwJWGACLZRF6cJ5bXldxqgCEU=,iv:UnsPuj72bakcuQC7mxL+IsQkXXrmdprtGpOYHhmwGCM=,tag:MnZlM2Fs1OsxANQiQOsFXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
