apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:RFN0uXuU4g0Lqjmro8HbkaZKNu6G7dYXILqdx4tc5UzJjq5VSWZ47w==,iv:CYdwyJWeSGhbchoFhubLjcOkafUFOwCo6DPTXv+BTRo=,tag:rNebarLDn2LNqz6fEV6yNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbHlFTVFEWWRQQmxNRmJR
            TngxR2VXcGFIK3dLenAvd0lXODhhS01lK0Y4CnJVSXFKZzBGNGlrL25VZ1JOc3cx
            SFY0ZHVSQlhVVEp3OEEyQU9kRk5aWlUKLS0tIDlqY2VwaklmRXJYSGs2VmRpb0l4
            aS85eGVCSjMvckFraUxMSEZUVS9PZmsKqIn4bguISyVJiiKabGSfLBXnk2mnw+Ro
            N1/xAbpTj48UNdY6aBBhQm645Po1x4ZiPD3eOJe93DXDIjAj0LxaPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:12:16Z"
    mac: ENC[AES256_GCM,data:+4Q2HDR8wE0QWjz8ySYpbkog3vSTKawWy+6n9AN0fC+VubBRcZPG5b2qXxX6EQHACxGBy72uwL2AxeuXoyXy3S7jBMcs6XSuefG4w2ds+57MGTko0y4WN7OSbQQHhhNoojz0re6gM3gfoxrLMtrkpI5WWGpEq7FQQYiHwRucqIE=,iv:CN/5Xtar+aApBPqdHx6YIIw7l84k3f1ev4I7zdxFfi8=,tag:ANLcyXmnPJy9aKPaKOzSOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
