apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:1LUQuOiJMdKnd+dYwgT1+bU5pFtPm9SUbdMBSTElH+yl8bvNvb801Q==,iv:+t2BV4cw8Yh34xLglTnqmlYD7+GYgWKiSvXK+1sb35c=,tag:EqhBukppMIHMMsDVACLCgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRHhYKzFPMG1ieURQd2kv
            US95czVsajAvUHNKTnNqRTRzdjV5WXMveFdNCk1vT1R4NlVjcnAydXJQQk9jS255
            Sm5PMUNqcHRFQmdBazBqbVdnNVBBT2cKLS0tIHFDN2w0NUhqakNrZE1PVy9XRkxp
            TjFXRU42VFEraXk0ZGhZdEZHN1YvbVkK9IJr3HVBmDS+w9h6LfbArpsJAzoTUxdU
            mMG02XYqXSM9ik1IxYrnevKgqRHLcTA3Ya8A8gl9jniIobLlTVvU4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:12:15Z"
    mac: ENC[AES256_GCM,data:XvoCfvObBQDQ4bVqfGdxT4M4qr6wuF4CXEmLtIo5J2rFFq+QCmRh4Ko0NBSUjWTeOEwycDwYeNkAb6IfoqmbbcR4AQnU6Fi1h4HwV8hkWssLWYuU2r6LwFfhb8qaNGdwinwVdrsR7aCOabDoKAS5SX2/ThGu9KnegbZEVPrMRSU=,iv:hrFqtgQYcyefy0/fOhyu+rabEXER2wc2nKHmmyjHOLQ=,tag:1GIxcyy8ojKKp48Vy7cqFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
