---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./discord-template-notifier/ks.yaml
  - ./atuin/ks.yaml
  - ./mosquitto/ks.yaml
  - ./node-red/ks.yaml
  - ./homebridge/ks.yaml
  - ./home-assistant/ks.yaml
