---
- name: Install and Configure NTP
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  vars:
    ntp_server: [10.0.10.1]
  tasks:
  - name: Install NTP
    apt: name=ntp update_cache=yes
  - name: Copy the ntp.conf template file
    template: src=ntp.conf.j2 dest=/etc/ntp.conf
    notify:
      - restart ntp
  handlers:
  - name: restart ntp
    service: name=ntp state=restarted
