---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-secret
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        # App
        BAZARR__API_KEY: "{{ .bazarr_api_key }}"
        POSTGRES_ENABLED: "true"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_HOST: &dbHost "{{ .init_postgres_host }}"
        POSTGRES_USERNAME: &dbUser "{{ .init_postgres_user }}"
        POSTGRES_PASSWORD: &dbPass "{{ .init_postgres_pass }}"
        POSTGRES_PORT: "5432"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .init_postgres_super_pass }}"
  data:
    - secretKey: init_postgres_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_host
    - secretKey: init_postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_user
    - secretKey: init_postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_pass
    - secretKey: init_postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e #cloudnative-pg-secret
        property: init_postgres_super_pass
    - secretKey: bazarr_api_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 0af85e1b-b516-43ef-a3a3-b0c90135acaa #media_secrets
        property: bazarr_api_key
