---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-gatus-ep
  namespace: flux-system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: echo-server
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: echo-server.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushovera
