---
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: echo-server
        group: external
        url: https://echo-server.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://10.0.10.1:53
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
