---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-gitops-gatus-ep
  namespace: flux-system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Wave GitOps
        group: guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: gitops.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushovera
