---
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-gitops-gatus-ep
  namespace: flux-system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Wave-GitOps
        group: internal
        url: https://gitops.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://10.0.10.1:53
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
