---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  refreshInterval: 5m
  target:
    name: alertmanager-secret
    deletionPolicy: Delete
    template:
      templateFrom:
        - configMap:
            name: alertmanager-config-tpl
            items:
              - key: alertmanager.yaml
  data:
    - secretKey: pushover_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8ed594de-ad74-45ec-a6ac-b0ba0029b835
        property: pushover_token
    - secretKey: pushover_user_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8ed594de-ad74-45ec-a6ac-b0ba0029b835
        property: pushover_user_key
    - secretKey: uptimerobot_heartbeat_url
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8ed594de-ad74-45ec-a6ac-b0ba0029b835
        property: uptimerobot_heartbeat_url
