---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Alert Manager
        group: internal
        url: https://alertmanager.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://10.0.10.1:53
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Prometheus
        group: internal
        url: https://prometheus.${SECRET_DOMAIN}
        interval: 1m
        client:
          dns-resolver: tcp://10.0.10.1:53
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: discord
