---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twingate
  namespace: networking
spec:
  target:
    name: twingate-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TWINGATE_NETWORK: |-
          {{ .twingate_network}}
        TWINGATE_ACCESS_TOKEN: |-
          {{ .twingate_access_token}}
        TWINGATE_REFRESH_TOKEN: |-
          {{ .twingate_refresh_token}}
  refreshInterval: 15m
  data:
    - secretKey: twingate_network
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e96ee6e3-1fb8-4049-a605-b0ba0043d59d
        property: twingate_network
    - secretKey: twingate_access_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: twingate_access_token
    - secretKey: twingate_refresh_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: twingate_refresh_token
