---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: twingate
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: connector
      version: 0.1.19
      sourceRef:
        kind: HelmRepository
        name: twingate
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    connector:
      existingSecret: "twingate-secret"
      network: "supermiguel"
      # accessToken: "${TWINGATE_ACCESS_TOKEN}"
      # refreshToken: "${TWINGATE_REFRESH_TOKEN}"
