apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qMrAVGZNs/WCEFDZLbiK,iv:AOEXLimdnh/QCefavJYDtD/lJs5n5TA/Uvnt9lsRI8g=,tag:Q8rV9SThxWtmX7YJYXWE1w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4T4t8wER5i0JA45akpgL1Ugs+wXgy2ZDlemBkZxmSGxOv2OH,iv:xKnhl50cz15ahohV9xnV0MGZGQGX4cvTThnL26Xi8mM=,tag:AaHzRvt4/5SyJKhcfxHo/g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mnHYuX4h43U=,iv:CARAkqbZ3IiUyKZpqHuZByhJFv/Oxii+Uofu207c4zQ=,tag:Y+H0DYEnTGzq6OaeMpXtvg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OVg4OGRsaDE3V2ZpaVpm
            RU5jbkkyRFZHeTlJUUZPUlIzZnVqenlFVnpNCmhWY2dSalRsdFkyeWsxWlZWN3Zj
            UFh1dVllWE1ScGZLVkw0SVArQUhXL2sKLS0tIHB2N0V6WEhqamp5ZWFjWjJsaGNp
            NTUyeHJDM091SEJmaDh4andIdVN2NUEKfNHUkZuCyJm7XlmH+Y+qP/YGZXPa0xGQ
            538FMd+jXU3tQcTpAtfpBs29SSl2Xt2Rxsmm42JV6akMqWLz1GsE4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:12:15Z"
    mac: ENC[AES256_GCM,data:XwRgjCtPyS2IKVMXw2iPCIO4BiWQnt8Qa/FuKbpiz/8EMB6G4ysEtcryJlmi2tzrH7IMQk84FD92T4vVYkbCvtVPmn7kJ/h4PmevTPsheQ4LUvoxKlBizrGou/y0ajGecPDLR25WWIXXP/8NEYOHP9QlgyDtjx1WlrpcqjbXSJE=,iv:f6daV5H7c3WGFRnHEPp21asV1blV7IINj3Fac05MCbc=,tag:rAoIweZ8uLtUf9BB+rhJew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
