apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:J7mADpHO02dgUyRH,iv:UiEdL5jttwXu1bZS/NBHW15J3mpf91bkiUMtQxLeWzQ=,tag:hA1PgIcAU7+nKGSlNt+K4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YTF0ekREWUd3cnptSDZK
            Tlc1VDZyYndldEI4RUorN2laSXZjUEN4RDJRCk9XMmJTTS9YN2Jadnk5d0pkVzVj
            bWJ0T0xuY1FTSU9aN0p5MFdEQ3o1NHcKLS0tIGU1ZmNJSnNGWktTaU5scE56a0Yv
            QWJNZG1xSmlqbnVSZ0JCQzdXVFhvYXcKdPzqK7WgRxu48oX5ByPoQ+6C0RP7Q+wI
            W4uTYuYtsT3n+LB+2ehieW9ffzugGfWzlYHwdjhf+BsJcIQoxgf5Pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:15:29Z"
    mac: ENC[AES256_GCM,data:noz27u47dNz2aHz6RmZxnLhMV5xPmYia2ymaSkf3chJVrFaaxd4zN0j5CQ0Tj1XPLNVi+E6oZCK5yOV0np2IjLGWlg2/5bydtb+cbe6d4xLSKgzIf0Kbv1Ev/ktWQc7aMFs3DBzrZEV7u/aqFOAn1FpB7CO+p3LVAg2MgJmb8Dc=,iv:hukgTFSZ8pT/YuFnnPUcAgDkFLF9svwu4uoCfDVbC2o=,tag:xpUV8H99hAQlOvWo45HNiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
