apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openspeedtest
  namespace: networking
spec:
  chart:
    spec:
      chart: app-template
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.5.0
  install:
    createNamespace: true
    remediation:
      retries: 5
  interval: 15m
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: openspeedtest/latest
              tag: v2.0.5@sha256:3e610c8f445e901252b92c498ff061d5762a3db4ecb499565909eaa8000a6e3a
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: OpenSpeedTest
          hajimari.io/icon: simple-icons:speedtest
        hosts:
          - host: &host "speedtest.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    service:
      main:
        ports:
          http:
            port: 3000
