---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: openspeedtest
  namespace: networking
spec:
  interval: 1h
  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: openspeedtest/latest
      tag: v2.0.4@sha256:cb5a3aded1648bf6dcb38746c283da8ef02a0105ed6499bcfae577bca88c0823

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: OpenSpeedTest
          hajimari.io/icon: simple-icons:Speedtest
        hosts:
          - host: &host "speedtest.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    service:
      main:
        ports:
          http:
            port: 3000
            protocol: TCP
