---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-longhorn
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/apps/longhorn-system/longhorn/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: cluster-secrets
  # dependsOn:
  #   - name: cluster-apps-external-secrets-stores
