---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-secret
  namespace: database
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: |-
          {{ .postgres_user }}
        password: |-
          {{ .postgres_password }}
        AWS_ACCESS_KEY_ID: |-
          {{ .r2_access_key_id }}
        AWS_SECRET_ACCESS_KEY: |-
          {{ .r2_secret_key }}
        SECRET_CLOUDFLARE_ACCOUNT_ID: |-
          {{ .secret_cloudflare_account_id }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_user
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_password
    - secretKey: r2_access_key_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f0778dae-7210-47e6-81e4-b0c800354b9a
        property: r2_access_key_id
    - secretKey: r2_secret_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f0778dae-7210-47e6-81e4-b0c800354b9a
        property: r2_secret_key
    - secretKey: secret_cloudflare_account_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: f0778dae-7210-47e6-81e4-b0c800354b9a
        property: secret_cloudflare_account_id
  # cloudnative-pg-secret -> 94e18bc4-3332-451e-b23c-b0b80013372e
  # cloudflare-r2 -> f0778dae-7210-47e6-81e4-b0c800354b9a
