---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  target:
    name: cloudnative-pg-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        POSTGRES_USER: |-
          {{ .postgres_user }}
        POSTGRES_PASSWORD: |-
          {{ .postgres_password }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_user
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_password
