apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:X35x8SLUkjnlRnoJKTETRXbjXwjKpa6xnPutkCwuPMb+rY1i,iv:k2e1x+WNN1l/jdPPrctxo94bW54e0hnI6k8yepljoGM=,tag:Pi4EMwLc7Fu3D/DU361QPQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:BaPEvWPRTU30UeaNy43wv7NYZl9cqqLQxHiXK6xcIZtc4rQ2foAbRNOSTYtIfDIPZbgB5U2fHXeWNnJ1IPEkZJORkXbU15M/VEXnkzKG1qhIuAGvX2XAHv5AbLQCEi4Few9vKWQf8eGnEjmhOc3Be52hFkqMytT/VQr6Hnw4OV/OiqmSBzsWM8iUTl5bhB4hA25R1FIMJCUSPHxZGWuiGgPvDUOVuojROrZkFZGukA==,iv:iB/KYCwRHKcOZ6om4eyYcyHzqNcwiy0pd7YUGKtRugU=,tag:kRJIJOz9UZ7OK6GXkECA4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rtcaj34psg3fgeepa5dfgxa2f5s7dyvt5sefnsaaq6zugzmgxpzsvjjzft
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabDgxRm92Q2s2MWRUYVR4
            NTdsRmFhOTRXMEFuMW1WazNRaEFHVDdnMldzCmNxMlY3bkd6S3hUSVhnQnNsNnpa
            dGpOdjRqMU5EV28ra1lYeUs4MTRjNnMKLS0tIERrQWVXSHV5NjB0c09RbmRDYjhm
            NEtGcG1Od1N2LzdtcnlhN1F6bTBVUFkKTSLzGix3fx3hdunTV0y1W96xxb8eAasc
            q/OoxqygfJYbYsoSCsfuhiSqQ2abj20zKaxdkMBA7TajwGuQ//Z4hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T17:12:16Z"
    mac: ENC[AES256_GCM,data:Dn5gvYkW8gR1cx5WHyrnV3xQu3aAI5NgNUMf7zepGiGq3rmCDTzPkq2DbioUXe8Db9mIDmJH2eDRrQbgmhYnqTyhjmW/K0u8nVi8ipAe8v4DUiP18Bd2wniSILDWZoemVLUMenTDP6YFH2MXHXKGmAoQWDLd6xYtkKaca1g5U68=,iv:5XFKQQxuIuH7fVW+pLuSX41hm6SI/1lHR799EyIs8LM=,tag:bSwtqLvpvwVpa4XxlpNOWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
