---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atuin
  namespace: default
spec:
  target:
    name: atuin-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ATUIN_DB_URI: "postgres://{{ .postgres_user }}:{{ .postgres_password }}@postgres-rw.database.svc.cluster.local/atuin"
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: |-
          {{ .init_postgres_host }}
        INIT_POSTGRES_USER: |-
          {{ .init_postgres_user }}
        INIT_POSTGRES_PASS: |-
          {{ .init_postgres_pass }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .init_postgres_super_pass }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_user
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_password
    - secretKey: init_postgres_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_host
    - secretKey: init_postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_user
    - secretKey: init_postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_pass
    - secretKey: init_postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_super_pass
  dataFrom:
    - extract:
        key: atuin
    - extract:
        key: cloudnative-pg
