---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atuin-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      # - name: atuin
      #   group: internal
      #   url: https://sh.${SECRET_DOMAIN}
      #   interval: 1m
      #   client:
      #     dns-resolver: tcp://10.0.10.1:53
      #   ui:
      #     hide-hostname: false
      #     hide-url: false
      #   conditions:
      #     - "[STATUS] == 200"
      #   alerts:
      #     - type: discord

      - name: DownStairs AP
        group: Hardware
        url: "icmp://10.0.0.71"
        interval: 1m
        # client:
        #   dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: discord
