---
apiVersion: v1
kind: ConfigMap
metadata:
  name: atuin-gatus-ep
  namespace: default
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: atuin
        group: Internal
        url: sh.${SECRET_DOMAIN}
        interval: 1m
        ui:
          hide-hostname: false
          hide-url: false
        conditions:
          - "len([BODY]) == 0"
          - "[STATUS] == 200"
        alerts:
          - type: discord
