---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: vpa
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.0.0
      resources:
        requests:
          cpu: 10m
          memory: 100M
        limits:
          memory: 200M
      extraArgs:
        pod-recommendation-min-cpu-millicores: 15
        pod-recommendation-min-memory-mb: 61
        storage: prometheus
        container-pod-name-label: pod
        container-name-label: container
        metric_for_pod_labels: kube_pod_labels{job="kube-state-metrics"}[8d]
        pod_name_label: pod
        pod_namespace_label: namespace
        prometheus-cadvisor-job-name: kubelet
        # prometheus-address: |-
        #   http://thanos-query.monitoring.svc.cluster.local:9090
        recommender-name: performance
        target-cpu-percentile: 0.99
    updater:
      enabled: false
    admissionController:
      enabled: false
