---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-v2
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
