---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: twingate-1
  namespace: networking
spec:
  target:
    name: twingate-1-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        TWINGATE_ACCESS_TOKEN: |-
          {{ .twingate_access_token}}
        TWINGATE_REFRESH_TOKEN: |-
          {{ .twingate_refresh_token}}
  refreshInterval: 15m
  data:
    - secretKey: twingate_access_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb0de4cd-a6f9-4bbe-a66a-b0c00011cd42
        property: twingate-1_access_token
    - secretKey: twingate_refresh_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb0de4cd-a6f9-4bbe-a66a-b0c00011cd42
        property: twingate-1_refresh_token
