---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
  namespace: monitoring
spec:
  target:
    name: gatus-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CUSTOM_PUSHOVER_APP_TOKEN: |-
          {{ .custom_pushover_app_token }}
        CUSTOM_PUSHOVER_USER_KEY: |-
          {{ .custom_pushover_user_key }}
        INIT_POSTGRES_DBNAME: |-
          {{ .init_postgres_dbname }}
        INIT_POSTGRES_HOST: |-
          {{ .init_postgres_host }}
        INIT_POSTGRES_USER: |-
          {{ .init_postgres_user }}
        INIT_POSTGRES_PASS: |-
          {{ .init_postgres_pass }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .init_postgres_super_pass }}
        # # App
        # CUSTOM_PUSHOVER_APP_TOKEN: "{{ .CUSTOM_PUSHOVER_APP_TOKEN }}"
        # CUSTOM_PUSHOVER_USER_KEY: "{{ .CUSTOM_PUSHOVER_USER_KEY }}"
        # # Postgres Init
        # INIT_POSTGRES_DBNAME: gatus
        # INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        # INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        # INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        # INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  refreshInterval: 15m
  data:
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_user
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_password
    - secretKey: custom_pushover_app_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: custom_pushover_app_token
    - secretKey: custom_pushover_user_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: custom_pushover_user_key
    - secretKey: init_postgres_dbname
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_dbname
    - secretKey: init_postgres_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_host
    - secretKey: init_postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_user
    - secretKey: init_postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_pass
    - secretKey: init_postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_super_pass
