---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
  namespace: monitoring
spec:
  target:
    name: gatus-secret
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DISCORD_WEBHOOK_URL: |-
          {{ .gatus_discord_webhook}}
        CUSTOM_PUSHOVER_APP_TOKEN: |-
          {{ .custom_pushover_app_token }}
        CUSTOM_PUSHOVER_USER_KEY: |-
          {{ .custom_pushover_user_key }}
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: |-
          {{ .init_postgres_host }}
        INIT_POSTGRES_USER: |-
          {{ .init_postgres_user }}
        INIT_POSTGRES_PASS: |-
          {{ .init_postgres_pass }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .init_postgres_super_pass }}
        SECRET_ENDPOINT: |-
          {{ .secret_endpoint }}
  refreshInterval: 15m
  data:
    - secretKey: gatus_discord_webhook
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: e96ee6e3-1fb8-4049-a605-b0ba0043d59d
        property: gatus_discord_webhook
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_user
    - secretKey: postgres_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: postgres_password
    - secretKey: custom_pushover_app_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8a48fcae-1cdf-4f64-bb7f-b0ba00414027
        property: custom_pushover_app_token
    - secretKey: custom_pushover_user_key
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 8a48fcae-1cdf-4f64-bb7f-b0ba00414027
        property: custom_pushover_user_key
    - secretKey: init_postgres_host
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_host
    - secretKey: init_postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_user
    - secretKey: init_postgres_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_pass
    - secretKey: init_postgres_super_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: init_postgres_super_pass
    - secretKey: secret_endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 94e18bc4-3332-451e-b23c-b0b80013372e
        property: secret_endpoint
